# Generated by Django 3.1.6 on 2021-02-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='memeurl',
            new_name='url',
        ),
    ]
